version: '3.8'

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: sh -c "npm install && node index.js"
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      database:
        condition: "service_healthy"

  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 20s
      timeout: 40s
      retries: 3

volumes:
  mysql:
    driver: mysql2